# Generated by Django 4.1.7 on 2023-04-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('web_honeypot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoneypotSettings',
            new_name='HoneypotSetting',
        ),
    ]
